### PR TITLE
fix: add original hl message check in deposit validation

### LINKED ISSUE #102: Fix validate deposit
There is no check that the HL message being signed is in the transaction or that the outpoint is in the HL message, thus any relayer can hijack someone elses deposit

### PR DESCRIPTION
**Pull request by srene**

### CODE REVIEW

**Review by danwt — CHANGES_REQUESTED** [review]
There are still things missing.

The validator signs the message ID and the payload.origin from the FXG, so these have to be shown to match.

Also, I don't think it makes sense to check 'field-wise' like this

```
    if original_token_message.amount() != token_message.amount() || original_token_message.recipient() != token_message.recipient(){
```
    
it's error prone. Why not compare bytes of the whole payload?

The the validator needs to check the outpoint is injected properly.
    
Please let's document the validation properly as well in the docstring so we can agree the intended behaviour is correct.

Additionally I think  function is very hard to read at least for me since all the variable names are similar, it would be better to split each step of the validation into another function I think

File: dymension/libs/kaspa/lib/relayer/src/deposit/deposit.rs [hunk 1]
```diff
@@ -15,15 +15,19 @@ use kaspa_consensus_core::tx::TransactionOutpoint;
 pub use secp256k1::PublicKey;
 use std::error::Error;
 
-struct ParsedHL {
-    hl_message: HyperlaneMessage,
-    token_message: TokenMessage,
+pub struct ParsedHL {
```
Comment (keruch) [inline dymension/libs/kaspa/lib/relayer/src/deposit/deposit.rs]: move this struct to `lib/core`? since it is used by both validator and relayer

Comment (srene) [reply dymension/libs/kaspa/lib/relayer/src/deposit/deposit.rs]: done

**Comment by srene** [comment]
> There are still things missing.
> 
> The validator signs the message ID and the payload.origin from the FXG, so these have to be shown to match.
> 
> Also, I don't think it makes sense to check 'field-wise' like this
> 
> ```
>     if original_token_message.amount() != token_message.amount() || original_token_message.recipient() != token_message.recipient(){
> ```
> 
> it's error prone. Why not compare bytes of the whole payload?
> 
> The the validator needs to check the outpoint is injected properly.
> 
> Please let's document the validation properly as well in the docstring so we can agree the intended behaviour is correct.
> 
> Additionally I think function is very hard to read at least for me since all the variable names are similar, it would be better to split each step of the validation into another function I think

i recreated the hl metadata injection in the original payload in Kaspa tx, and then compared hl messages ids to validate the whole hl messages content are the same

**Review by keruch — DISMISSED** [review]
