### PR TITLE
fix: refactor sweeping to avoid transfer escrow funds to relayer 

### LINKED ISSUE #268: unable to validate sweeping transaction
this happens because sweeping generator used moves funds to temporarily to relayer address when multiple sweeping tx are required due to the high number of inputs. new sweeping function is required since the sweeping generator from kaspa wallet does not seem useful in our case (where we sweep escrow inputs but relayer pay for fees).

### PR DESCRIPTION
**Pull request by srene**
This PR fixes sweeping problem when using PSKTGenerator that moves funds temporarily to escrow address when multi-level sweeping is required.
* The solution implements a new sweeping function that chains multiple sweeping txs to avoid moving funds to relayer address and the relayer keeps paying for txs.
* The max mass check is refactored since it was conflicting with sweeping. 
* Sweeping is limited to MAX_SWEEP_INPUTS = 1000 (only in case it covers withdrawals amount) to avoid exploiting small deposits to increase withdrawal latency.

### CODE REVIEW

File: dymension/libs/kaspa/lib/relayer/src/withdraw/messages.rs [hunk 1]
```diff
@@ -114,11 +108,25 @@ pub async fn build_withdrawal_fxg(
...
+        let total_withdrawal_amount: u64 = outputs.iter().map(|o| o.value).sum();
+
+        // Get anchor amount (not swept but available for withdrawals)
+        let anchor_amount = anchor_input.1.amount; // anchor_input is (TransactionInput, UtxoEntry, Option<Vec<u8>>)
+
+        // Calculate total withdrawal amount needed
+        let total_withdrawal_amount: u64 = outputs.iter().map(|o| o.value).sum();
+
+        // Get anchor amount (not swept but available for withdrawals)
+        let anchor_amount = anchor_input.1.amount; // anchor_input is (TransactionInput, UtxoEntry, Option<Vec<u8>>)
```
Comment (danwt) [inline dymension/libs/kaspa/lib/relayer/src/withdraw/messages.rs]: duplicated lines

File: dymension/libs/kaspa/lib/relayer/src/withdraw/messages.rs [hunk 2]
```diff
@@ -148,17 +156,72 @@ pub async fn build_withdrawal_fxg(
...
+                MessageIDs::from(&final_msgs).to_bytes(),
+                relayer.net.network_id,
+                escrow_public.m() as u16,
+            )
+            .map_err(|e| eyre::eyre!("Estimate TX mass after output removal: {e}"))?;
+        }
+    }
+
+    if final_outputs.len() < original_count {
+        info!(
```
Comment (danwt) [inline dymension/libs/kaspa/lib/relayer/src/withdraw/messages.rs]: unused import: `super::*`rustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20[0]?0#file:///Users/danwt/Documents/dym/d-hyperlane-monorepo/dymension/libs/kaspa/lib/relayer/src/withdraw/messages.rs)
messages.rs(198, 5): remove the whole `use` item

File: dymension/libs/kaspa/lib/relayer/src/withdraw/messages.rs [hunk 3]
```diff
@@ -148,17 +156,72 @@ pub async fn build_withdrawal_fxg(
...
+        MessageIDs::from(&final_msgs).to_bytes(),
+        relayer.net.network_id,
+        escrow_public.m() as u16,
+    )
+    .map_err(|e| eyre::eyre!("Estimate TX mass: {e}"))?;
+
+    // Use tx_fee_multiplier as safety margin for mass limit too
+    // This ensures we stay under the limit even with estimation variance
+    let max_allowed_mass = (kaspa_wallet_core::tx::MAXIMUM_STANDARD_TRANSACTION_MASS as f64
+        / tx_fee_multiplier) as u64;
```
Comment (danwt) [inline dymension/libs/kaspa/lib/relayer/src/withdraw/messages.rs]: fee multipler is a dollar value multiplier, it shouldnt be in a mass calculation

File: dymension/libs/kaspa/lib/relayer/src/withdraw/messages.rs [hunk 4]
```diff
@@ -148,17 +156,72 @@ pub async fn build_withdrawal_fxg(
...
+
+    if final_outputs.len() < original_count {
+        info!(
+            "Kaspa relayer, reduced withdrawals from {} to {} due to mass limit. Final mass: {} (limit with margin: {})",
+            original_count,
+            final_outputs.len(),
+            tx_mass,
+            max_allowed_mass
+        );
+    }
```
Comment (danwt) [inline dymension/libs/kaspa/lib/relayer/src/withdraw/messages.rs]: branch is pointless, you can always log this
also dont interpolate logs

File: dymension/libs/kaspa/lib/relayer/src/withdraw/messages.rs [hunk 5]
```diff
@@ -169,9 +232,9 @@ pub async fn build_withdrawal_fxg(
     // The last element is the withdrawal PSKT, so it should have all the HL messages.
     let messages = {
         let sweep_count = sweeping_bundle.as_ref().map_or(0, |b| b.0.len());
-        let mut messages = Vec::with_capacity(sweep_count + valid_msgs.len());
+        let mut messages = Vec::with_capacity(sweep_count + final_msgs.len());
         messages.extend(vec![Vec::new(); sweep_count]);
-        messages.push(valid_msgs);
+        messages.push(final_msgs);
         messages
```
Comment (danwt) [inline dymension/libs/kaspa/lib/relayer/src/withdraw/messages.rs:230]: this function is now way too long to read/deeply indented, need to extra sub functions

File: dymension/libs/kaspa/lib/relayer/src/withdraw/sweep.rs [hunk 6]
```diff
@@ -4,129 +4,469 @@ use corelib::escrow::EscrowPublic;
...
-    let signer = relayer_wallet
-        .pskb_signer()
-        .await
-        .map_err(|e| eyre::eyre!("Create PSKB signer: {}", e))?;
-
-    let pskt_gen = PSKTGenerator::new(
-        generator,
-        Arc::new(signer),
-        relayer_wallet.net.address_prefix,
+    // Track total swept amount and number of inputs processed
```
Comment (danwt) [inline dymension/libs/kaspa/lib/relayer/src/withdraw/sweep.rs]: useless comment

File: dymension/libs/kaspa/lib/relayer/src/withdraw/sweep.rs [hunk 7]
```diff
@@ -4,129 +4,469 @@ use corelib::escrow::EscrowPublic;
...
+    let mut total_swept_amount = 0u64;
+    let mut total_inputs_swept = 0usize;
+
+    // Calculate how much more we need to sweep considering the anchor amount
+    let effective_withdrawal_amount = if anchor_amount >= total_withdrawal_amount {
+        0 // Anchor already covers all withdrawals, no need to sweep for withdrawal amount
+    } else {
+        total_withdrawal_amount - anchor_amount
+    };
```
Comment (danwt) [inline dymension/libs/kaspa/lib/relayer/src/withdraw/sweep.rs]: should be one line with min and max funcs

File: dymension/libs/kaspa/lib/relayer/src/withdraw/sweep.rs [hunk 8]
```diff
@@ -4,129 +4,469 @@ use corelib::escrow::EscrowPublic;
...
-    let pskt_gen = PSKTGenerator::new(
-        generator,
-        Arc::new(signer),
-        relayer_wallet.net.address_prefix,
+    // Track total swept amount and number of inputs processed
+    let mut total_swept_amount = 0u64;
+    let mut total_inputs_swept = 0usize;
+
+    // Calculate how much more we need to sweep considering the anchor amount
+    let effective_withdrawal_amount = if anchor_amount >= total_withdrawal_amount {
```
Comment (danwt) [inline dymension/libs/kaspa/lib/relayer/src/withdraw/sweep.rs]: what does effective_withdrawal_amount mean, why not call it needToSweepAmt if thats what the comment says

File: dymension/libs/kaspa/lib/hardcode/src/tx.rs [hunk 9]
```diff
@@ -45,4 +45,6 @@ Blue Score Difference (d)	Time Elapsed (Approx)	Upper Bound on Reorg Probability
 We choose 1000, which is probably over conservative.
  */
 pub const REQUIRED_FINALITY_BLUE_SCORE_CONFIRMATIONS: i64 = 1000;
-pub const FINALITY_APPROX_WAIT_TIME: Duration = Duration::from_secs(100 + 3); // give a bit of leeway
+
+// Maximum number of inputs to include in a sweeping bundle.
+pub const MAX_SWEEP_INPUTS: usize = 1000;
```
Comment (danwt) [inline dymension/libs/kaspa/lib/hardcode/src/tx.rs:50]: I dont get it, this is two orders of magnitude more than @keruch found would be maximum inputs
did you test with playground escrow? (6 of 8 multisig)?

File: dymension/libs/kaspa/lib/relayer/src/withdraw/sweep.rs [hunk 10]
```diff
@@ -4,129 +4,469 @@ use corelib::escrow::EscrowPublic;
...
+        total_withdrawal_amount - anchor_amount
+    };
+    info!(
+        "Kaspa sweeping: need to sweep {} sompi (total withdrawals {} sompi - anchor {} sompi)",
+        effective_withdrawal_amount, total_withdrawal_amount, anchor_amount
     );
+    // Process escrow inputs recursively until:
+    // 1. All are consumed, OR
+    // 2. We have enough for withdrawals AND reached the maximum number of inputs (1000)
+    while !escrow_inputs.is_empty() {
```
Comment (danwt) [inline dymension/libs/kaspa/lib/relayer/src/withdraw/sweep.rs:343]: why not sorting inputs by size descending first?

File: dymension/libs/kaspa/lib/relayer/src/withdraw/sweep.rs [hunk 11]
```diff
@@ -4,129 +4,469 @@ use corelib::escrow::EscrowPublic;
...
+        // Check if we've swept enough to cover withdrawals AND reached the maximum inputs
+        if total_swept_amount >= effective_withdrawal_amount
+            && total_inputs_swept >= MAX_SWEEP_INPUTS
```
Comment (danwt) [inline dymension/libs/kaspa/lib/relayer/src/withdraw/sweep.rs:346]: why is this &&

**Review by danwt — CHANGES_REQUESTED** [review]

File: dymension/libs/kaspa/lib/relayer/src/withdraw/sweep.rs [hunk 12]
```diff
@@ -4,129 +4,469 @@ use corelib::escrow::EscrowPublic;
...
+    let test_outputs = vec![
+        TransactionOutput {
+            value: total_escrow_balance,
+            script_public_key: escrow.p2sh.clone(),
+        },
+        TransactionOutput {
+            value: total_relayer_balance,
+            script_public_key: pay_to_address_script(relayer_address),
+        },
+    ];
```
Comment (danwt) [inline dymension/libs/kaspa/lib/relayer/src/withdraw/sweep.rs]: duplicated below

Please can you dry the code out you have to QA claude please

**Review by danwt — CHANGES_REQUESTED** [review]
```
Looking at the codebase, the PopulatedInput tuple (TransactionInput, UtxoEntry, Option<Vec<u8>>) is created in many places with slight variations. Here's
  the detailed analysis:

  Current Duplication Instances

  1. In sweep.rs - prepare_next_iteration_inputs() (lines 260-290)

  // Relayer input creation
  let relayer_input = (
      TransactionInput::new(
          TransactionOutpoint::new(tx_id, relayer_idx),
          vec![],
          u64::MAX,
          RELAYER_SIG_OP_COUNT,
      ),
      UtxoEntry::new(
          relayer_output.amount,
          relayer_output.script_public_key.clone(),
          UNACCEPTED_DAA_SCORE,
          false,
      ),
      None,
  );

  // Escrow input creation (similar pattern, different values)
  let escrow_input = (
      TransactionInput::new(
          TransactionOutpoint::new(tx_id, escrow_idx),
          vec![],
          u64::MAX,
          escrow.n() as u8,
      ),
      UtxoEntry::new(
          escrow_output.amount,
          escrow_output.script_public_key.clone(),
          UNACCEPTED_DAA_SCORE,
          false,
      ),
      Some(escrow.redeem_script.clone()),
  );

  2. In sweep.rs - create_inputs_from_sweeping_bundle() (lines 496-519)

  // Almost identical to above, just different variable names
  let relayer_input: PopulatedInput = (
      TransactionInput::new(
          TransactionOutpoint::new(tx_id, relayer_idx),
          vec![],
          u64::MAX,
          RELAYER_SIG_OP_COUNT,
      ),
      UtxoEntry::new(
          relayer_output.amount,
          relayer_output.script_public_key.clone(),
          UNACCEPTED_DAA_SCORE,
          false,
      ),
      None,
  );

  let escrow_input: PopulatedInput = (
      TransactionInput::new(
          TransactionOutpoint::new(tx_id, escrow_idx),
          vec![],
          u64::MAX,
          escrow.n() as u8,
      ),
      UtxoEntry::new(
          escrow_output.amount,
          escrow.p2sh.clone(),
          UNACCEPTED_DAA_SCORE,
          false,
      ),
      Some(escrow.redeem_script.clone()),
  );

  3. In hub_to_kaspa.rs - fetch_input_utxos() (lines 554-577)

  populated_inputs.push((
      TransactionInput {
          previous_outpoint: TransactionOutpoint {
              transaction_id: utxo.entry.outpoint.transaction_id.into(),
              index: utxo.entry.outpoint.index,
          },
          signature_script: vec![],
          sequence: u64::MAX,
          sig_op_count: sigop_count,
      },
      UtxoEntry::new(
          utxo.entry.amount,
          utxo.entry.script_public_key.clone(),
          utxo.entry.block_daa_score,
          utxo.entry.is_coinbase,
      ),
      redeem_script.clone(),
  ));

  4. In test code (lines 740-754)

  let inputs: Vec<PopulatedInput> = (0..input_count)
      .map(|_i| {
          (
              TransactionInput {
                  previous_outpoint: TransactionOutpoint {
                      transaction_id: Hash::from_bytes([0u8; 32]),
                      index: 0,
                  },
                  signature_script: vec![],
                  sequence: u64::MAX,
                  sig_op_count: 1,
              },
              UtxoEntry {
                  amount: 100000,
                  script_public_key: ScriptPublicKey::from_vec(0, vec![]),
                  block_daa_score: 0,
                  is_coinbase: false,
              },
              None,
          )
      })
      .collect();

  The Problems

  1. Repeated Boilerplate: Every creation has the same structure with different parameters
  2. Error-Prone: Easy to mix up field ordering or forget fields
  3. Inconsistent Construction: Some use TransactionInput::new(), others use struct literals
  4. Magic Values: u64::MAX for sequence, UNACCEPTED_DAA_SCORE, empty vec![] repeated everywhere
  5. No Type Safety: The tuple doesn't express what each component represents

```

File: dymension/libs/kaspa/lib/relayer/src/withdraw/messages.rs (hunk 2 above)
Comment (srene) [reply dymension/libs/kaspa/lib/relayer/src/withdraw/messages.rs]: are you sure are you revising things from this pr? i dont see any added import in the file from this pr. super::* removed

File: dymension/libs/kaspa/lib/relayer/src/withdraw/messages.rs (hunk 1 above)
Comment (srene) [reply dymension/libs/kaspa/lib/relayer/src/withdraw/messages.rs]: cleaned

File: dymension/libs/kaspa/lib/relayer/src/withdraw/messages.rs (hunk 4 above)
Comment (srene) [reply dymension/libs/kaspa/lib/relayer/src/withdraw/messages.rs]: tbh i dont see where is the problem but i removed it if its going to be a problem

File: dymension/libs/kaspa/lib/relayer/src/withdraw/sweep.rs (hunk 12 above)
Comment (srene) [reply dymension/libs/kaspa/lib/relayer/src/withdraw/sweep.rs]: done

File: dymension/libs/kaspa/lib/relayer/src/withdraw/messages.rs (hunk 3 above)
Comment (srene) [reply dymension/libs/kaspa/lib/relayer/src/withdraw/messages.rs]: replaced by new const param

File: dymension/libs/kaspa/lib/hardcode/src/tx.rs (hunk 9 above)
Comment (srene) [reply dymension/libs/kaspa/lib/hardcode/src/tx.rs:50]: i test everything i code. this is not per tx. is maximum sweeping done for the same bundle (batch) to avoid spending too much time sweeping when there are lots of pending utxos from deposits without withdrawing. limitations are based on max mass per tx.

File: dymension/libs/kaspa/lib/relayer/src/withdraw/sweep.rs (hunk 11 above)
Comment (srene) [reply dymension/libs/kaspa/lib/relayer/src/withdraw/sweep.rs:346]: already explained

File: dymension/libs/kaspa/lib/relayer/src/withdraw/sweep.rs (hunk 8 above)
Comment (srene) [reply dymension/libs/kaspa/lib/relayer/src/withdraw/sweep.rs]: renamed to withdrawal_amount_without_anchor

File: dymension/libs/kaspa/lib/relayer/src/withdraw/sweep.rs (hunk 6 above)
Comment (srene) [reply dymension/libs/kaspa/lib/relayer/src/withdraw/sweep.rs]: sure

File: dymension/libs/kaspa/lib/relayer/src/withdraw/sweep.rs (hunk 7 above)
Comment (srene) [reply dymension/libs/kaspa/lib/relayer/src/withdraw/sweep.rs]: done

File: dymension/libs/kaspa/lib/relayer/src/withdraw/sweep.rs (hunk 10 above)
Comment (srene) [reply dymension/libs/kaspa/lib/relayer/src/withdraw/sweep.rs:343]: done

File: dymension/libs/kaspa/lib/relayer/src/withdraw/messages.rs (hunk 5 above)
Comment (srene) [reply dymension/libs/kaspa/lib/relayer/src/withdraw/messages.rs:230]: moved logic to new func adjust_outputs_for_mass_limit

**Comment by srene** [comment]
> ```
> Looking at the codebase, the PopulatedInput tuple (TransactionInput, UtxoEntry, Option<Vec<u8>>) is created in many places with slight variations. Here's
>   the detailed analysis:
> 
>   Current Duplication Instances
> 
>   1. In sweep.rs - prepare_next_iteration_inputs() (lines 260-290)
> 
>   // Relayer input creation
>   let relayer_input = (
>       TransactionInput::new(
>           TransactionOutpoint::new(tx_id, relayer_idx),
>           vec![],
>           u64::MAX,
>           RELAYER_SIG_OP_COUNT,
>       ),
>       UtxoEntry::new(
>           relayer_output.amount,
>           relayer_output.script_public_key.clone(),
>           UNACCEPTED_DAA_SCORE,
>           false,
>       ),
>       None,
>   );
> 
>   // Escrow input creation (similar pattern, different values)
>   let escrow_input = (
>       TransactionInput::new(
>           TransactionOutpoint::new(tx_id, escrow_idx),
>           vec![],
>           u64::MAX,
>           escrow.n() as u8,
>       ),
>       UtxoEntry::new(
>           escrow_output.amount,
>           escrow_output.script_public_key.clone(),
>           UNACCEPTED_DAA_SCORE,
>           false,
>       ),
>       Some(escrow.redeem_script.clone()),
>   );
> 
>   2. In sweep.rs - create_inputs_from_sweeping_bundle() (lines 496-519)
> 
>   // Almost identical to above, just different variable names
>   let relayer_input: PopulatedInput = (
>       TransactionInput::new(
>           TransactionOutpoint::new(tx_id, relayer_idx),
>           vec![],
>           u64::MAX,
>           RELAYER_SIG_OP_COUNT,
>       ),
>       UtxoEntry::new(
>           relayer_output.amount,
>           relayer_output.script_public_key.clone(),
>           UNACCEPTED_DAA_SCORE,
>           false,
>       ),
>       None,
>   );
> 
>   let escrow_input: PopulatedInput = (
>       TransactionInput::new(
>           TransactionOutpoint::new(tx_id, escrow_idx),
>           vec![],
>           u64::MAX,
>           escrow.n() as u8,
>       ),
>       UtxoEntry::new(
>           escrow_output.amount,
>           escrow.p2sh.clone(),
>           UNACCEPTED_DAA_SCORE,
>           false,
>       ),
>       Some(escrow.redeem_script.clone()),
>   );
> 
>   3. In hub_to_kaspa.rs - fetch_input_utxos() (lines 554-577)
> 
>   populated_inputs.push((
>       TransactionInput {
>           previous_outpoint: TransactionOutpoint {
>               transaction_id: utxo.entry.outpoint.transaction_id.into(),
>               index: utxo.entry.outpoint.index,
>           },
>           signature_script: vec![],
>           sequence: u64::MAX,
>           sig_op_count: sigop_count,
>       },
>       UtxoEntry::new(
>           utxo.entry.amount,
>           utxo.entry.script_public_key.clone(),
>           utxo.entry.block_daa_score,
>           utxo.entry.is_coinbase,
>       ),
>       redeem_script.clone(),
>   ));
> 
>   4. In test code (lines 740-754)
> 
>   let inputs: Vec<PopulatedInput> = (0..input_count)
>       .map(|_i| {
>           (
>               TransactionInput {
>                   previous_outpoint: TransactionOutpoint {
>                       transaction_id: Hash::from_bytes([0u8; 32]),
>                       index: 0,
>                   },
>                   signature_script: vec![],
>                   sequence: u64::MAX,
>                   sig_op_count: 1,
>               },
>               UtxoEntry {
>                   amount: 100000,
>                   script_public_key: ScriptPublicKey::from_vec(0, vec![]),
>                   block_daa_score: 0,
>                   is_coinbase: false,
>               },
>               None,
>           )
>       })
>       .collect();
> 
>   The Problems
> 
>   1. Repeated Boilerplate: Every creation has the same structure with different parameters
>   2. Error-Prone: Easy to mix up field ordering or forget fields
>   3. Inconsistent Construction: Some use TransactionInput::new(), others use struct literals
>   4. Magic Values: u64::MAX for sequence, UNACCEPTED_DAA_SCORE, empty vec![] repeated everywhere
>   5. No Type Safety: The tuple doesn't express what each component represents
> ```

Added PopulatedInputBuilder, although i think it has minimal impact and only helps in 3 and 5. regarding 4 i suggest you open an issue with that, since it has nothing to do with this pr.

File: dymension/libs/kaspa/lib/hardcode/src/tx.rs (hunk 9 above)
Comment (danwt) [reply dymension/libs/kaspa/lib/hardcode/src/tx.rs:50]: gotcha thx
Yeah sorry I know you test everything I was just confused

**Review by danwt — APPROVED** [review]
good job 👍
