### PR TITLE
fix:  discard withdrawal tx on deposit detection

### LINKED ISSUE #131: withdraw detected as deposit in relayer
although it does not pass relayer validations and its discarded, its initially logged as new deposit and there maybe some way to better filter deposits. this is caused by withdrawal tx includes outpoints with escrow address as destination.

### PR DESCRIPTION
**Pull request by srene**
### Description
it discards withdrawals in deposit detection in logic loop by checking there is no input from the escrow address in the transaction detected.

Closes #131

### CODE REVIEW

File: rust/main/hyperlane-base/src/kas_hack/logic_loop.rs [hunk 1]
```diff
@@ -153,6 +168,33 @@ where
...
+    /// Check if a deposit is genuine by verifying the escrow address is not in the transaction inputs
+    /// Returns true if it's a genuine deposit, false if it's likely a withdrawal
+    async fn is_genuine_deposit(&self, deposit: &Deposit, escrow_address: &str) -> Result<bool> {
+        // Fetch full transaction details with inputs
+        let tx = self
+            .provider
+            .rest()
+            .client
+            .client
+            .get_tx_by_id(&deposit.id.to_string())
```
Comment (danwt) [inline rust/main/hyperlane-base/src/kas_hack/logic_loop.rs]: isn't this expensive? dont. you want a block hint?

File: rust/main/hyperlane-base/src/kas_hack/logic_loop.rs [hunk 2]
```diff
@@ -153,6 +168,33 @@ where
         }
     }
 
+    /// Check if a deposit is genuine by verifying the escrow address is not in the transaction inputs
+    /// Returns true if it's a genuine deposit, false if it's likely a withdrawal
+    async fn is_genuine_deposit(&self, deposit: &Deposit, escrow_address: &str) -> Result<bool> {
```
Comment (danwt) [inline rust/main/hyperlane-base/src/kas_hack/logic_loop.rs]: isn't just checking the payload contains HL message enough?

**Review by danwt — CHANGES_REQUESTED** [review]
I dont get it, why dont check payload?

File: rust/main/hyperlane-base/src/kas_hack/logic_loop.rs (hunk 1 above)
Comment (srene) [reply rust/main/hyperlane-base/src/kas_hack/logic_loop.rs]: no

File: rust/main/hyperlane-base/src/kas_hack/logic_loop.rs (hunk 2 above)
Comment (srene) [reply rust/main/hyperlane-base/src/kas_hack/logic_loop.rs]: replaced

**Comment by srene** [comment]
> I dont get it, why dont check payload?

i dont think there is a big difference, but i modified to use payload instead to save one network request.

File: rust/main/hyperlane-base/src/kas_hack/logic_loop.rs [hunk 3]
```diff
@@ -138,11 +138,26 @@ where
...
+                        self.deposit_cache.mark_as_seen(d.clone()).await;
+                        deposits_new.push(d);
+                    }
+                    Ok(false) => {
+                        info!(deposit_id = %d.id, "Dymension, skipping deposit with invalid or missing Hyperlane payload");
+                        self.deposit_cache.mark_as_seen(d.clone()).await;
+                    }
+                    Err(e) => {
+                        error!(deposit_id = %d.id, error = ?e, "Dymension, failed to check if deposit is genuine, skipping");
+                        self.deposit_cache.mark_as_seen(d.clone()).await;
```
Comment (danwt) [inline rust/main/hyperlane-base/src/kas_hack/logic_loop.rs]: should by dryer

**Review by danwt — CHANGES_REQUESTED** [review]

**Comment by danwt** [comment]
I dont get it because relayer_on_new_deposit is already checking for payload, so why dont just handle the error in https://github.com/dymensionxyz/hyperlane-monorepo/blob/2250772cc7691c74a4a61b883698afe69e72ff28/rust/main/hyperlane-base/src/kas_hack/logic_loop.rs#L228

File: rust/main/hyperlane-base/src/kas_hack/logic_loop.rs (hunk 3 above)
Comment (srene) [reply rust/main/hyperlane-base/src/kas_hack/logic_loop.rs]: done

**Comment by srene** [comment]
> I dont get it because relayer_on_new_deposit is already checking for payload, so why dont just handle the error in
> 
> https://github.com/dymensionxyz/hyperlane-monorepo/blob/2250772cc7691c74a4a61b883698afe69e72ff28/rust/main/hyperlane-base/src/kas_hack/logic_loop.rs#L228

because when fail to process it will requeue. this is an easy way to filter out withdrawals before processing

**Review by danwt — APPROVED** [review]
