### PR TITLE
fix: wait for pending confirmation before new withdrawal process

### LINKED ISSUE #161: Relayer withdraws too soon after previous, it should wait for confirmation
2025-07-18T09:28:15.308602Z ERROR relayer::msg::op_submitter: Error when submitting kaspa batch, error: EyreError(Fetch input UTXOs: No UTXOs found for current anchor: TransactionOutpoint { transaction_id: 0750d7b6b5e99d116698a9c69c3b646dbb86048443affcb89b8b3f7b5db94fa1, index: 2 } escrow: kaspatest:pq35y32hs3h0kyp7gmrsutl5mhlrhnf889quax65dlhcw8ym2kgdzm4hhz3qe (ScriptHash)

### PR DESCRIPTION
**Pull request by srene**

### CODE REVIEW

File: rust/main/chains/dymension-kaspa/src/mailbox.rs [hunk 1]
```diff
@@ -151,6 +151,18 @@ impl Mailbox for KaspaMailbox {
...
+        loop {
+            if !self.provider.is_there_pending_confirmation() {
+                info!("Kaspa mailbox: No pending confirmation found. Proceeding with batch.");
+                time::sleep(time::Duration::from_secs(5)).await;
+                break; // Exit loop if no pending confirmation
+            }
+            info!("Kaspa mailbox: Pending confirmation found. Waiting before re-checking.");
+            // Use tokio::time::sleep for async waiting
+            time::sleep(time::Duration::from_secs(1)).await;
+        }
```
Comment (keruch) [inline rust/main/chains/dymension-kaspa/src/mailbox.rs]: do you think we need this loop? can we use native hyperlane retries? https://github.com/dymensionxyz/hyperlane-monorepo/blob/f25ca22b17efbce1ad3d093988c3b876a5890f7b/rust/main/agents/relayer/src/msg/op_batch.rs#L76-L100

File: rust/main/chains/dymension-kaspa/src/providers/confirmation_queue.rs [hunk 2]
```diff
@@ -12,12 +14,22 @@ impl PendingConfirmation {
             mutex: Mutex::new(None),
         }
     }
-    pub fn consume(&self) -> Option<ConfirmationFXG> {
+
+    /// consume waits a FINALITY_APPROX_WAIT_TIME before returning ConfirmationFXG when there is a pending one
+    pub async fn consume(&self) -> Option<ConfirmationFXG> {
+        if self.has_pending(){
+            time::sleep(FINALITY_APPROX_WAIT_TIME).await;
+        }
```
Comment (keruch) [inline rust/main/chains/dymension-kaspa/src/providers/confirmation_queue.rs]: `PendingConfirmation` is just a data structure, I think it shouldn't know about any business logic. I'd leave `time::sleep` in the kas_hack loop.

Comment (srene) [reply rust/main/chains/dymension-kaspa/src/providers/confirmation_queue.rs]: agree. moved

File: rust/main/chains/dymension-kaspa/src/mailbox.rs (hunk 1 above)
Comment (srene) [reply rust/main/chains/dymension-kaspa/src/mailbox.rs]: i replaced by pending confirmation check in mailbox. if there is pending it fails and it will retry again including failed ops.

File: rust/main/hyperlane-base/src/kas_hack/logic_loop.rs [hunk 3]
```diff
@@ -206,15 +206,20 @@ where
...
+            let confirmation = self.provider.get_pending_confirmation().await;
 
             match confirmation {
                 Some(confirmation) => {
-                    time::sleep(FINALITY_APPROX_WAIT_TIME).await;
                     let res = self.confirm_withdrawal_on_hub(confirmation.clone()).await;
                     match res {
                         Ok(_) => {
                             info!("Dymension, confirmed withdrawal on hub: {:?}", confirmation);
+                            self.provider.consume_pending_confirmation();
```
Comment (keruch) [inline rust/main/hyperlane-base/src/kas_hack/logic_loop.rs:211]: just to note, if `confirm_withdrawal_on_hub` fails, we will retry it indefinitely unless we restart the relayer. in theory, it can only fail if double spending happens after the reorg (we discussed it a few days ago), maybe it's not really probable for us since we do all operations sequentially.

**Review by keruch — DISMISSED** [review]

File: rust/main/hyperlane-base/src/kas_hack/logic_loop.rs (hunk 3 above)
Comment (danwt) [reply rust/main/hyperlane-base/src/kas_hack/logic_loop.rs:211]: > if double spending happens after the reorg (we discussed it a few days ago)
wdym @keruch ?, this should be impossible

Comment (danwt) [inline rust/main/hyperlane-base/src/kas_hack/logic_loop.rs:211]: I dont really get the changes in this progress_indication_loop tbh? Could you explain @srene ?
Seems buggy anyway because you can consume a different confirmation than the one you confirmed if the thread hangs between confirm_withdrawal_on_hub and consume_pending_confirmation

File: rust/main/agents/relayer/src/msg/op_submitter.rs [hunk 4]
```diff
@@ -583,45 +583,37 @@ async fn submit_classic_task(
...
-            }
-            std::cmp::Ordering::Equal => {
-                let op = batch.pop().unwrap();
-                submit_single_operation(op, &mut prepare_queue, &mut confirm_queue, &metrics).await;
-            }
-            std::cmp::Ordering::Greater => {
-                OperationBatch::new(batch, domain.clone())
-                    .submit(&mut prepare_queue, &mut confirm_queue, &metrics)
-                    .await;
-            }
```
Comment (danwt) [inline rust/main/agents/relayer/src/msg/op_submitter.rs]: why you delete it?

**Review by danwt — CHANGES_REQUESTED** [review]
I dont' think the approach in op_submitter is good because

- it forks upstream a lot, we should keep changes isolated to kaspa branches only (is_kas(..){..})
- no discrimination on the failure reason, you assume all can be retried
- sleep unnecessarily
- there is already facility for op rescheduling

Tbh I though it would be a case of 
- making sure the relayer process_batch returns appropriate error to discriminate failure reasons for every message
- fixing the todos here to reschudule using the existing rescheduling method https://github.com/dymensionxyz/hyperlane-monorepo/blob/3fcaa1cada9b8993ec77975625227bf497e725c8/rust/main/agents/relayer/src/msg/op_submitter.rs#L1100-L1138

That would be much more correct in each failure reason, and more close to upstream and a lot cleaner I think

File: rust/main/hyperlane-base/src/kas_hack/logic_loop.rs (hunk 3 above)
Comment (keruch) [reply rust/main/hyperlane-base/src/kas_hack/logic_loop.rs:211]: I suggested this change to cover this issue https://github.com/dymensionxyz/hyperlane-monorepo/issues/140#issuecomment-3079140956

You consume the confirmation on this line (214) https://github.com/dymensionxyz/hyperlane-monorepo/blob/e82b2ad25aa84a82af00ff9a33c5f76f6c66c011/rust/main/hyperlane-base/src/kas_hack/logic_loop.rs#L214

After this, the relayer can take on a new batch

But we confirm the previous batch on the Hub after the consumption (218) https://github.com/dymensionxyz/hyperlane-monorepo/blob/e82b2ad25aa84a82af00ff9a33c5f76f6c66c011/rust/main/hyperlane-base/src/kas_hack/logic_loop.rs#L218

If the relayer takes on a new batch between lines 214 and 218 in logic_loop.rs, then the batch fails bc the Hub outpoint is still the old one

So we get the confirmation without consuming it and then actually consume at the end of the loop. And `has_pending_confirmation` returns `true` until we finally confirm on the Hub.

> you can consume a different confirmation than the one you confirmed 

You can't. `process_batch` is the one who puts a new confirmation and it can't go to the next iteration until the previous confirmation is consumed. Ref: https://github.com/dymensionxyz/hyperlane-monorepo/pull/173/files#diff-2704e49a8742b78cfb556de0df22d47a8426a83b8b7fb262f321d7360217b560R155

File: rust/main/agents/relayer/src/msg/op_submitter.rs (hunk 4 above)
Comment (srene) [reply rust/main/agents/relayer/src/msg/op_submitter.rs]: its never executed but ill readded to avoid future issues with upstream changes

File: rust/main/hyperlane-base/src/kas_hack/logic_loop.rs (hunk 3 above)
Comment (srene) [reply rust/main/hyperlane-base/src/kas_hack/logic_loop.rs:222]: i dont think this can happen because pending confirmation will block any other thread

Comment (srene) [reply rust/main/hyperlane-base/src/kas_hack/logic_loop.rs:211]: i think any issue caused by failing in confirm_withdrawal_on_hub() its outside of the scope of this pr. its true  the relayer will need to be restarted if this happens, but it will be necessary anyway before the changes.

Comment (danwt) [reply rust/main/hyperlane-base/src/kas_hack/logic_loop.rs:211]: yeah thanks Kirill! Sergi explained to me on a call
